### ISSUE TITLE
Курсовой проект 2015

### ISSUE THREAD

**Issue by AlexChernov** [AlexChernov/course-project#1]
Тема:
Разработка системы автоматизированной сборки, тестирования и развертывания системы Rao X
Листы:
- [x] Лист 1. А1. [Постановка задачи](https://github.com/AlexChernov/course-project/blob/2015/Листы/list1.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2015/Листы/list1.pdf)
- [x] Лист 2. А1. [Диаграмма пакетов Rao X.](https://github.com/AlexChernov/course-project/blob/2015/Листы/list2.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2015/Листы/list2.pdf)
- [x] Лист 3. А2. [Топология системы автоматизированной сборки, тестирвоания и развертывания](https://github.com/AlexChernov/course-project/blob/2015/Листы/list3.1.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2015/Листы/list3.1.pdf)
- [x] Лист 4. А2. [Диаграмма развертывания системы автоматизированной сборки, тестирования и развертывания.](https://github.com/AlexChernov/course-project/blob/2015/Листы/list3.2.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2015/Листы/list3.2.pdf)
- [x] Лист 5. А2. [Диаграмма активности системы автоматизированной сборки, тестирования и развертывания.](https://github.com/AlexChernov/course-project/blob/2015/Листы/list4.1.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2015/Листы/list4.1.pdf)
- [x] Лист 6. А2. [Диаграмма компонентов скрипта сборки](https://github.com/AlexChernov/course-project/blob/2015/Листы/list4.2.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2015/Листы/list4.2.pdf)
- [x] Лист 7. А1. [Результаты](https://github.com/AlexChernov/course-project/blob/2015/Листы/list5.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2015/Листы/list5.pdf)

Штампы
- [x] [Штампы](https://github.com/AlexChernov/course-project/blob/2015/Листы/штампы.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2015/Листы/штампы.pdf)

РПЗ
- [x] [ПЗ](https://github.com/AlexChernov/course-project/blob/2015/pz.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2015/pz.pdf)

**Comment by AlexChernov** [comment]
@aurusov

**Comment by aurusov** [comment]
- Лист 8. Штампы
- РПЗ

**Comment by aurusov** [comment]
- Лист 1. А1. Постановка задачи **[на печать]**
- Лист 2. А1. Диаграмма пакетов Rao X **[на печать]**
- Лист 3. А2. Топология системы автоматизированной сборки, тестирвоания и развертывания **[на печать]**
- Лист 4. А2. Диаграмма развертывания системы автоматизированной сборки, тестирования и развертывания **[на печать]**
- Лист 5. А2. Диаграмма активности системы автоматизированной сборки, тестирования и развертывания **[на печать]**
- Лист 6. А2. Диаграмма коммуникации скрипта сборки
  - Это разве диаграмма коммуникации/компонентов ? Откуда брал примеры ? В записке он называется `Архитектура скрипта автоматической сборки и развертывания`. Мне нравится, но это не ГОСТ. Надо свести к UML или к Aris. Или смириться с тем, что это плакат.
- Лист 7. А1. Результаты **[на печать]**
- Штампы **[на печать]**
- РПЗ
  - ~~Цель в ТЗ пусть будет как тема~~ Имелось в виду `Полное наименование темы разработки` - `Разработка системы автоматизированной сборки, тестирования и развертывания системы Rao X`

**Comment by aurusov** [comment]
посмотрел

**Comment by AlexChernov** [comment]
Добавил РПЗ, если сегодня все исправлю, завтра будет возможность с утра подписать?

**Comment by AlexChernov** [comment]
Лист 1. А1. Постановка задачи
обновил
Лист 3. А2. Топология системы автоматизированной сборки, тестирвоания и развертывания

> Почему у Кафедрального сервера есть Сайт Rao X ?

 Исправил

Лист 4. А2. Диаграмма развертывания системы автоматизированной сборки, тестирования и развертывания

> Разве мы используем для сборки Power shell, а не bash ?

 PowerShell -> shell

> Что означает направление у стрелки на диаграмме ? Кажется, что стрелка посередине должна быть наверх.

Убрал стрелку, так как там двусторонняя связь и http запрос и http ответ

Лист 6. А2. Диаграмма коммуникации скрипта сборки

> Это разве диаграмма коммуникации ? Откуда брал примеры ?

Изменил название на диаграмма компонентов
![Пример](http://khpi-iip.mipk.kharkiv.edu/library/case/leon/gl10/gl10-5.jpg)

**Comment by aurusov** [comment]
Обновил

**Comment by AlexChernov** [comment]
Лист 6. А2. Диаграмма компонентов скрипта сборки
Диаграмма компонентов, Component diagram — статическая структурная диаграмма, показывает разбиение программной системы на структурные компоненты и связи (зависимости) между компонентами.
Исправлю в РПЗ на "Структура скрипта автоматической сборки и развертывания"
![Пример](https://cloud.githubusercontent.com/assets/7085247/11994050/8e0aff96-aa49-11e5-9684-5108350fa5ba.jpg)

**Comment by AlexChernov** [comment]
Лист 1. Исправил
Рпз. Исправил

**Comment by aurusov** [comment]
Обновил, остальное нужно голосом. Наберу.
