### ISSUE TITLE
2016 Консультация по листам

### ISSUE THREAD

**Issue by AlexChernov** [AlexChernov/course-project#2]
Тема:
Разработка системы автоматизированной сборки, тестирования и развертывания системы Rao X
Листы:
- [x] Лист 1. А1. [Постановка задачи](https://github.com/AlexChernov/course-project/blob/2016/publish/list1.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2016/publish/list1.pdf)
- [x] Лист 2. А2. [Диаграмма пакетов системы Rao X.](https://github.com/AlexChernov/course-project/blob/2016/publish/list2.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2016/publish/list2.pdf)
- [x] Лист 3. А2. [as-is синтаксическая диаграмма cобираемых показателей](https://github.com/AlexChernov/course-project/blob/2016/publish/list3.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2016/publish/list3.pdf)
- [x] Лист 4. А3. [to-be синтаксическая диаграмма cобираемых показателей](https://github.com/AlexChernov/course-project/blob/2016/publish/list4.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2016/publish/list4.pdf)
- [x] Лист 5. А2. [Диаграмма классов собираемых показателей](https://github.com/AlexChernov/course-project/blob/2016/publish/list5.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2016/publish/list5.pdf)
- [x] Лист 5.2. А3. [Блок-схема методов WeightedStorelessNumericStatistics](https://github.com/AlexChernov/course-project/blob/2016/publish/list8.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2016/publish/list8.pdf)
- [x] Лист 6. А1. [Диаграмма последовательности собираемых показателей](https://github.com/AlexChernov/course-project/blob/2016/publish/list6.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2016/publish/list6.pdf)
- [x] Лист 7. А1. [Результаты](https://github.com/AlexChernov/course-project/blob/2016/publish/list7.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2016/publish/list7.pdf)
- [x] [Штампы](https://github.com/AlexChernov/course-project/blob/2016/publish/osn.nadpis.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2016/publish/osn.nadpis.pdf)
- [x] [РПЗ](https://github.com/AlexChernov/course-project/blob/2016/publish/pz.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2016/publish/pz.pdf)

**Comment by AlexChernov** [comment]
@aurusov

**Comment by AlexChernov** [comment]
Защита в четверг

**Comment by aurusov** [comment]
В какой ?

**Comment by AlexChernov** [comment]
В этот, завтра

**Comment by aurusov** [comment]
Оптимистично. Прямо сейчас посмотерть не могу.

**Comment by aurusov** [comment]
Лист 1. А1. Постановка задачи, ok, **[на печать]**
Лист 2. А2. Диаграмма пакетов системы Rao X, ok, **[на печать]**
Лист 3. А2. as-is синтаксическая диаграмма cобираемых показателей, ok, **[на печать]**
Лист 4. А3. to-be синтаксическая диаграмма cобираемых показателей, ok, **[на печать]**
Лист 5. А2. Диаграмма классов собираемых показателей, ok, **[на печать]**
- Переделал в А2 ?

Лист 5.2. А3. Блок-схема методов WeightedStorelessNumericStatistics, ok, **[на печать]**
Лист 6. А1. Диаграмма последовательности собираемых показателей, ok, **[на печать]**
Лист 7. А1. Результаты, ok, **[на печать]**

Штампы, ok, **[на печать]**

Записка, ok, **[на печать]**

**Comment by aurusov** [comment]
Замечания по листам. Про размеры уже написал, стараюсь не высказывать то, о чем думаю. Ну ты понял. Теперь о позитивном. На листах не отражено, что теперь отдельно источники данных, отдельно обработка. Это кажется качественным отличием от того, что было. Плюс не отражено, что сейчас можно собирать в двух режимах, автоматическом и ручном.

**Comment by aurusov** [comment]
Записка.
- требования в тз кажутся заниженными, но пусть так
- не хватает описания CategoricalStatistics, StorelessNumericStatistics и др. Кстати, почему бы не вынести их работу в виде пары блок-схем на листы ? До утра еще куча времени. Понятно, что больше А1x5 не надо.
- `Разработана грамматика и соответствующие синтаксические диаграммы, разработаны необходимы абстрактные классы`
 - Какие именно аб. классы ?
 - Они есть на диаграмме классов ?
 - Они разработаны тобой или уже были ?
- `Была разработана документация по функционалу системы, являющейся руководством по его использованию на сервере или персональном компьютере` - Где она ?

**Comment by AlexChernov** [comment]
> Непонятно, что ты хотел сказать таблицей. Если я правильно понял, то невозможно собрать статистику по двум последним строкам. Поясни.

Да, то что невозможно собраться статистику по двум последним строкам

> Лист 2. А1. Диаграмма пакетов системы Rao X
> Кажется надо делать в А2. Какой размер шрифта сейчас, какой получится ?

Это и есть А2, исправил

> ссылка битая

Исправил

> Лист 5. А1. Диаграмма классов собираемых показателей
> Это тоже А2. Какие шрифты ?

upd. Calibri 24

**Comment by aurusov** [comment]
Обновил замечания по листам

**Comment by AlexChernov** [comment]
> На листах не отражено, что теперь отдельно источники данных, отдельно обработка. Это кажется качественным отличием от того, что было. Плюс не отражено, что сейчас можно собирать в двух режимах, автоматическом и ручном.

Не понятно как это показывать на листах. `отдельно источники данных, отдельно обработка` это хотел сказать во время доклада на листе с грамматикой, это еще видно на диаграмме последовательностей.
`сейчас можно собирать в двух режимах, автоматическом и ручном`
поправлю на диаграмме последовательностей, чтобы было видно ручной режим и тоже можно во время доклада сказать, на листах с грамматикой, диаграммой классов и на диаграмме последовательностей

**Comment by aurusov** [comment]
> Не понятно как это показывать на листах.

Надо попробовать

> поправлю на диаграмме последовательностей, чтобы было видно ручной режим и тоже можно во время доклада сказать

На диаграмме можно, но на плакате должно быть нагляднее.

**Comment by AlexChernov** [comment]
> Лист 5. А1. Диаграмма классов собираемых показателей
> - Подготовь А2, хочу сравнить
> - Вместо одного листа - 4-ре, исправь pdf

[A1, calibri 24](https://github.com/AlexChernov/course-project/blob/2016/publish/list5.pdf) [A2, calibri 18](https://github.com/AlexChernov/course-project/blob/2016/publish/list5.1.pdf)

**Comment by AlexChernov** [comment]
Записка.

> не хватает описания CategoricalStatistics, StorelessNumericStatistics и др. Кстати, почему бы не вынести их работу в виде пары блок-схем на листы ? До утра еще куча времени. Понятно, что больше А1x5 не надо.

Небольшое описание есть в рабочем проектировании

> Разработана грамматика и соответствующие синтаксические диаграммы, разработаны необходимы абстрактные классы
> 
> > Какие именно аб. классы ?

Result, Statistics это есть в техническом проектировании, исправил

> > Они есть на диаграмме классов ?

  Есть

> > Они разработаны тобой или уже были ?

  Разработаны мной

> Была разработана документация по функционалу системы, являющейся руководством по его использованию на сервере или персональном компьютере - Где она ?

Убрал копипасту

**Comment by aurusov** [comment]
> A1, calibri 24 A2, calibri 18

Оба смотрятся норм, давай оставим текущий. Если будет нужен дополнительный лист А2, то уменьшим этот.

**Comment by aurusov** [comment]
> Небольшое описание есть в рабочем проектировании

Именно что небольшое. Хочется больше. Напиши для человека, который через год откроет твою записку, чтобы разобраться.

**Comment by aurusov** [comment]
Обновил итого. Больше всего смущает, что лист результатов не раскрывает крутизну проделанной работы.

**Comment by AlexChernov** [comment]
> Непонятно, что ты хотел сказать таблицей. Если я правильно понял, то невозможно собрать статистику по двум последним строкам. Мне кажется возможным. Поясни.
> 
> > Статистика по типам звонков 

В текущей версии нет статистики по перечисляемым переменным, ее точно нельзя, поэтому же `Статистика по занятости операторов` под вопросом, пока у нее 2 состояния статистику можно собрать

> > Статистика по длительности разговоров 

В текущей версии нет взвешенной по количеству вхождений статистики для числовых переменных

**Comment by AlexChernov** [comment]
Исправил таблицы на [листе 1](https://github.com/AlexChernov/course-project/blob/2016/publish/list1.pdf)
Исправил [лист результатов](https://github.com/AlexChernov/course-project/blob/2016/publish/list1.pdf)
Добавил [блок схему](https://github.com/AlexChernov/course-project/blob/2016/publish/list8.pdf) одной статистики

**Comment by AlexChernov** [comment]
> не хватает описания CategoricalStatistics, StorelessNumericStatistics и др.

Расписал подробнее

**Comment by AlexChernov** [comment]
Завтра видимо тоже не успеваю

**Comment by aurusov** [comment]
![-3](https://cloud.githubusercontent.com/assets/5585202/15978145/118fb834-2f65-11e6-8680-c50a1b279f0f.png)

**Comment by aurusov** [comment]
Можно печатать, только 5-ый лист не в том формате.

**Comment by aurusov** [comment]
Подготовь материалы для выкладки на сайт.

**Comment by AlexChernov** [comment]
[publish](https://github.com/AlexChernov/course-project/raw/2016/publish/publish.zip)
[source](https://github.com/AlexChernov/course-project/raw/2016/publish/source.zip)

**Comment by aurusov** [comment]
Выложил
