### ISSUE TITLE
Консультация 2017

### ISSUE THREAD

**Issue by AlexChernov** [AlexChernov/course-project#3]
Тема:
 Доработка системы автоматизированной сборки, тестирования и развертывания системы Rao X
Листы:
- [ ] Лист 1. А1. [Постановка задачи](https://github.com/AlexChernov/course-project/blob/2017/pdf/1.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2017/pdf/1.pdf)
- [ ] Лист 2. А2. [Диаграмма пакетов системы Rao X.](https://github.com/AlexChernov/course-project/blob/2017/pdf/2.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2017/pdf/2.pdf)
- [ ] Лист 3. А3. [as-is синтаксическая диаграмма cобираемых показателей](https://github.com/AlexChernov/course-project/blob/2017/pdf/3.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2017/pdf/3.pdf)
- [ ] Лист 4. А3. [to-be синтаксическая диаграмма cобираемых показателей](https://github.com/AlexChernov/course-project/blob/2017/pdf/4.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2017/pdf/4.pdf)
- [ ] Лист 5. А2. [Блок-схема компилирования собираемых показателей](https://github.com/AlexChernov/course-project/blob/2017/pdf/5.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2017/pdf/5.pdf)
- [ ] Лист 6. А1. [Диаграмма классов собираемых показателей](https://github.com/AlexChernov/course-project/blob/2017/pdf/6.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2017/pdf/6.pdf)
- [ ] Лист 7. А1. [Диаграмма последовательности построения графиков собираемых показателей](https://github.com/AlexChernov/course-project/blob/2017/pdf/7.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2017/pdf/7.pdf)
- [ ] Лист 8. А2. [Результаты](https://github.com/AlexChernov/course-project/blob/2017/pdf/8.pdf) [(raw)](https://github.com/AlexChernov/course-project/raw/2017/pdf/8.pdf)
- [ ] [Штампы]
- [ ] [РПЗ](https://github.com/AlexChernov/course-project/blob/2017/pdf/pz.pdf)[(raw)](https://github.com/AlexChernov/course-project/raw/2017/pdf/pz.pdf)

**Comment by AlexChernov** [comment]
@aurusov

**Comment by AlexChernov** [comment]
https://github.com/AlexChernov/course-project/blob/2017/pdf/pz.pdf

**Comment by aurusov** [comment]
Посмотрел, можно печатать всё.
